baseURL = 'https://iucommonground.github.io/'
languageCode = 'en-us'
title = 'Common Ground 2025'
theme = 'hugo-simple'


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]


[params]
title = "Hugo Simple"
description = "Hugo Simple Demo"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = true
custom_css = ["css/custom.css"]

[params.author]
name = "commonground"
email = "commonground@gmail.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Keynotes"
pageRef = "/friday"
weight = 20

[[menu.main]]
name = "Film Screenings"
pageRef = "/screenings"
weight = 30

[[menu.main]]
name = "Panels"
pageRef = "/saturday"
weight = 40




[pagination]
pagerSize = 16
